### PR TITLE
feat: add indentmini.nvim

### PR DESCRIPTION
**Pull request by xiaoshihou514**
Just a plugin I have been using :)

### CODE REVIEW

**Comment by xiaoshihou514** [comment]
The dependency order for `guard.nvim` and `guard-collection` seem to be reversed, hopefully the CI is able to handle this.

**Comment by xiaoshihou514** [comment]
Hmm, if I think about it `guard-collection` doesn't necessarily _depend_ on `guard.nvim`, it just won't do anything useful without it. It's probably not meant to be installed standalone.
Not sure what's the best take on this.

**Review by mrcjkb — CHANGES_REQUESTED** [review]
Thanks 🙏

The guard.nvim dependency is fine as it was.
Most people are probably going to want to use it and luarocks dependencies don't have a meaningful impact on startup time.

**Comment by xiaoshihou514** [comment]
Right, I will revert it.

**Review by mrcjkb — APPROVED** [review]

**Comment by xiaoshihou514** [comment]
Thanks!

**Pull request merged**
