### PR TITLE
feat: add nvim-lsp-file-operations plugin

### PR DESCRIPTION
**Pull request by mikavilpas**
The project's readme reads:

> Neovim plugin that adds support for file operations using built-in LSP
>
> nvim-lsp-file-operations is a Neovim plugin that adds support for file
> operations using built-in LSP support. This plugin works by
> subscribing to events emitted by nvim-tree and neo-tree. But other
> integrations are possible.
>
> https://github.com/antosha417/nvim-lsp-file-operations

Note that while the project's readme specifies other dependencies besides plenary.nvim, it seems they are actually optional and not strictly required.

I'm working on adding a new integration to this project from my own project to help achieve a more stable LSP integration (https://github.com/mikavilpas/yazi.nvim/issues/80). Since I added luarocks support to my project a while ago, I would love to be able to support users preferring luarocks for their plugin management.

### CODE REVIEW

**Review by mrcjkb — APPROVED** [review]
@teto have you fixed the issues with dependencies?

**Comment by teto** [comment]
there is https://github.com/nvim-neorocks/nurr/pull/13 that should fix the workflow

**Comment by mikavilpas** [comment]
Thanks so much! Looks like the rock can now be found here https://luarocks.org/modules/neorocks/nvim-lsp-file-operations

👍🏻

**Comment by teto** [comment]
I am a big fan of yazi and have been curious to test yazi.nvim so helping youy helps me and FOSS wins \o/

**Pull request merged**
