### PR TITLE
change "dependencies" from a string to a list of strings

### PR DESCRIPTION
**Pull request by teto**
I am doing some changes on luarocks-tag-release to be able to run it locally with as stdin a subset of the plugins.json. The "dependencies" as a string was an annoyance and anyway it's cleaner to have it structured. 
I need them to join the list as a string for luarocks-tag-release to work with luarocks-tag-release but as I am unsure how to do that with github DSL, testing here

### CODE REVIEW

**Comment by teto** [comment]
turned out github workflow has a `join` function that does just that.

**Comment by mrcjkb** [comment]
[Readme needs an update](https://github.com/nvim-neorocks/nurr?tab=readme-ov-file#schema) :)

**Comment by teto** [comment]
it borke the workflow because the concatenation is not good https://github.com/nvim-neorocks/nurr/actions/runs/9888890852/job/27313793850#step:4:489 :/ I should have added a basic generation in the PR test. I will do a follow up

**Comment by teto** [comment]
will try to fix this in https://github.com/nvim-neorocks/nurr/pull/13

**Pull request merged**
